# uosc UI
mbtn_right  script-binding uosc/menu
menu        script-binding uosc/menu
tab         script-binding uosc/toggle-ui

# Playback
space       cycle pause; script-binding uosc/flash-pause-indicator
right       seek  5
left        seek -5
shift+right seek  30; script-binding uosc/flash-timeline
shift+left  seek -30; script-binding uosc/flash-timeline
.           frame-step
,           frame-back-step

# Volume
m           no-osd cycle mute; script-binding uosc/flash-volume
up          no-osd add volume  5; script-binding uosc/flash-volume
down        no-osd add volume -5; script-binding uosc/flash-volume
WHEEL_UP    no-osd add volume  2; script-binding uosc/flash-volume
WHEEL_DOWN  no-osd add volume -2; script-binding uosc/flash-volume

# Speed
[           no-osd add speed -0.1; script-binding uosc/flash-speed
]           no-osd add speed  0.1; script-binding uosc/flash-speed
\           no-osd set speed  1.0; script-binding uosc/flash-speed

# uosc menus
s           script-binding uosc/subtitles       #! Subtitles
a           script-binding uosc/audio            #! Audio Tracks
p           script-binding uosc/playlist          #! Playlist
c           script-binding uosc/chapters          #! Chapters
o           script-binding uosc/open-file         #! Open File

# Quality menu
F           script-binding quality_menu/video_formats_toggle  #! Stream Quality > Video
alt+f       script-binding quality_menu/audio_formats_toggle  #! Stream Quality > Audio
ctrl+r      script-binding quality_menu/reload

# Playlist
>           playlist-next
<           playlist-prev
ctrl+l      ab-loop

# Screenshots
S           screenshot video
ctrl+s      screenshot

# Window
f           cycle fullscreen
q           quit

# Subtitles
v           cycle sub-visibility
j           cycle sub
J           cycle sub down
