timeline_style=line
timeline_line_width=2
timeline_size=40
timeline_persistency=paused,audio
timeline_step=5

controls=menu,gap,<video,audio>subtitles,<has_many_audio>audio,<has_many_video>video,<stream>stream-quality,gap,space,speed,space,shuffle,loop-playlist,loop-file,gap,prev,items,next,gap,fullscreen

volume_size=40
volume_step=1

top_bar=no-border
top_bar_title=${media-title}

speed_step=0.1
speed_step_is_factor=no

menu_type_to_search=yes
